import time
import numpy as np

v = np.zeros(4000)
w = np.ones(4000)
I = np.eye(4000) # Matrix I

start = time.time()

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)


w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)


w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)
w = np.dot(I,v)

end = time.time()

t = end - start
print "np :", t
